steps:
  # Build, push frontend
  - name: gcr.io/cloud_builders/docker
    args: ['build', '-t', '$_FRONTEND_IMAGE', '-f', 'K8s/frontend.Dockerfile', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_FRONTEND_IMAGE']

  # deploy frontend
  - name: gcr.io/cloud-builders/kubectl
    args: [ 'delete', 'deployments', '--all' ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-c
      - CLOUDSDK_CONTAINER_CLUSTER=cmiyc-cluster
      - CLOUDSDK_CORE_PROJECT=cmiyc-346518

  - name: gcr.io/cloud-builders/kubectl
    args: [ 'apply', '-f', 'K8s/deployment.yml' ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-c
      - CLOUDSDK_CONTAINER_CLUSTER=cmiyc-cluster
      - CLOUDSDK_CORE_PROJECT=cmiyc-346518


substitutions:
  _REGION                 : europe-central2
  _PROJECT_ID             : cmiyc-manage-349411
  _ARTIFACT_REGISTRY      : cmiyc-docker-repo
  _FRONTEND_IMAGE         : ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/frontend:latest
