steps:
  # Build, push frontend
  - name: gcr.io/cloud_builders/docker
    args: ['build', '-t', '$_FRONTEND_IMAGE', '-f', 'K8s/frontend.Dockerfile', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_FRONTEND_IMAGE']

  # Build, push authority
  - name: gcr.io/cloud_builders/docker
    args: ['build', '-t', '$_AUTHORITY_IMAGE', '-f', 'K8s/authority.Dockerfile', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_AUTHORITY_IMAGE']

  # delete all old deployments
  - name: gcr.io/cloud-builders/kubectl
    args: [ 'delete', 'deployments', '--all' ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-c
      - CLOUDSDK_CONTAINER_CLUSTER=cmiyc-cluster
      - CLOUDSDK_CORE_PROJECT=cmiyc-346518

  # create new deployments
  - name: gcr.io/cloud-builders/kubectl
    args: [ 'apply', '-f', 'K8s/deployment.yml' ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-c
      - CLOUDSDK_CONTAINER_CLUSTER=cmiyc-cluster
      - CLOUDSDK_CORE_PROJECT=cmiyc-346518


substitutions:
  _FRONTEND_IMAGE         : europe-central2-docker.pkg.dev/cmiyc-manage-349411/cmiyc-docker-repo/frontend:latest
  _AUTHORITY_IMAGE        : europe-central2-docker.pkg.dev/cmiyc-manage-349411/cmiyc-docker-repo/authority:latest