server:
  port: 8080

eureka:
  client:
  service-url:
  default-zone: http://localhost:8761/eureka

spring:
  application:
    name: connector
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json