server:
  port: ${PORTS_MICROSERVICES_CONNECTOR:8080}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: false

api:
  connections:
    rest-server:
      name: api1
      path: ${ROUTES_EXTERNAL_REST:http://localhost:9001}/rest
      type: rest
      method: post
    soap-server:
      name: api2
      path: ${ROUTES_EXTERNAL_SOAP:http://localhost:9003}/soap
      type: soap
      method: post
    websocket-server:
      name: api3
      path: ${ROUTES_EXTERNAL_WEBSOCKET:ws://localhost:9002}/ws
      type: websocket
      timeout: 10000

spring:
  application:
    name: connector
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ROUTES_MICROSERVICES_AUTHORITY:http://localhost:8090}/.well-known/jwks.json