server:
  port: ${PORTS_MICROSERVICES_CONNECTOR:8080}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: false

api:
  rest:
    name: NCIC
    path: ${ROUTES_EXTERNAL_REST:http://localhost:9001}/rest
    method: post
  soap:
    name: FRED
    path: ${ROUTES_EXTERNAL_SOAP:http://localhost:9003}/soap
    method: post
  websocket:
    name: DataGOV
    path: ${ROUTES_EXTERNAL_WEBSOCKET:ws://localhost:9002}/ws
    timeout: 10000

spring:
  application:
    name: connector
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ROUTES_MICROSERVICES_AUTHORITY:http://localhost:8090}/.well-known/jwks.json