server:
  port: ${PORTS_MICROSERVICES_CONNECTOR}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: false

api:
  connections:
    rest-server:
      name: api1
      path: ${ROUTES_EXTERNAL_REST}/rest
      type: rest
      method: post
    soap-server:
      name: api2
      path: ${ROUTES_EXTERNAL_SOAP}/soap
      type: soap
      method: post
    websocket-server:
      name: api3
      path: ${ROUTES_EXTERNAL_WEBSOCKET}/ws
      type: websocket
      timeout: 2000

spring:
  application:
    name: connector
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ROUTES_MICROSERVICES_AUTHORITY}/.well-known/jwks.json