version: "3.8"
services:
  mock-repository:
    image: external-apis/mock-repository
    restart: unless-stopped
    ports:
      - "9000:9000"
  soap-server:
    image: external-apis/soap-server
    depends_on:
      - mock-repository
    restart: on-failure
    ports:
      - "9003:9003"
    environment:
      ROUTES_EXTERNAL_MOCK_REPOSITORY: ws://mock-repository:9000
    stdin_open: true
    tty: true
  rest-server:
    image: external-apis/rest-server
    depends_on:
      - mock-repository
    restart: on-failure
    ports:
      - "9001:8080"
    environment:
      ROUTES_EXTERNAL_MOCK_REPOSITORY: ws://mock-repository:9000
    stdin_open: true
    tty: true
  websocket-server:
    image: external-apis/websocket-server
    depends_on:
      - mock-repository
    restart: on-failure
    ports:
      - "9002:8080"
    environment:
      ROUTES_EXTERNAL_MOCK_REPOSITORY: ws://mock-repository:9000
    stdin_open: true
    tty: true