apiVersion: v1
kind: Service
metadata:
  name: authority
spec:
  selector:
    app: authority
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mock-repository
spec:
  selector:
    app: mock-repository
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: soap-server
spec:
  selector:
    app: soap-server
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: rest-server
spec:
  selector:
    app: rest-server
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
spec:
  selector:
    app: websocket-server
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 8080