-- Inserting thirty test users: password of all: pass; 10 users, 10 admin_u, 10 admin_s
INSERT INTO cmiyc_authority_db.users (first_name, last_name, email, is_active, tfa_secret, password) VALUES
('Alehandro', 'Johnson', 'alehandro@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Remi', 'Furi', 'remi@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Mari', 'Tuna', 'mari@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Alex', 'Un', 'alex@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Totoro', 'Push', 'totoro@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Peter', 'Parker', 'parker@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Murad', 'Zely', 'murad@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Zoe', 'Fill', 'zoe@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Robert', 'Downey', 'robert@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Luisa', 'Oldsman', 'luisa@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Pavel', 'Sea', 'pavel@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Richard', 'Hell', 'richard@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Mali', 'Hell', 'mali@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Sem', 'Bred', 'sem@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Wendy', 'Oldsman', 'wendy@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Mari', 'Un', 'un@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Dumi', 'Du', 'du@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Robert', 'Lee', 'lee@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Peter', 'Johnson', 'peter@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Kailey', 'Lee', 'kailey@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Sue', 'Brain', 'brain@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Alexa', 'September', 'alexa@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Ken', 'Leaf', 'ken@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Alex', 'Leaf', 'alex2@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Britney', 'Spears', 'britney@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Loki', 'Lafeyson', 'loki@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Steve', 'Rogers', 'steve@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Black', 'Widow', 'black@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Thor', 'Odinson', 'thor@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6'),
('Steven', 'Strange', 'steven@gmail.com', true, 'OFO3LVPJRZDLUCYZEZDUZRN65T26ZZAF', '$2a$08$j9ArZIiXVOwvolOkM2Q//uZl9Lx5K7IFlzEVQHizi.V/w22IlMbe6');

-- Adding roles to users
INSERT INTO cmiyc_authority_db.users_roles (id_user, id_role) VALUES
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'alehandro@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'remi@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'mari@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'alex@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'totoro@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'parker@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'murad@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'zoe@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'robert@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'luisa@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'pavel@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'richard@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'mali@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'sem@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'wendy@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'un@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'du@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'lee@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'peter@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'kailey@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_user')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'brain@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'alexa@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'ken@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'alex2@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'britney@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'loki@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'steve@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'black@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'thor@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema')),
((SELECT id FROM cmiyc_authority_db.users WHERE email = 'steven@gmail.com'), (SELECT id from cmiyc_authority_db.roles WHERE role = 'admin_schema'));
