server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka

routes:
  microservices:
    authority:
      root: http://localhost:8090
      jwks: ${routes.microservices.authority.root}/.well-known/jwks.json

spring:
  application:
    name: search
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${routes.microservices.authority.jwks}
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30s