server:
  port: ${PORTS_MICROSERVICES_SEARCH:8082}

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka
    enabled: false

spring:
  application:
    name: search
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ROUTES_MICROSERVICES_AUTHORITY:http://localhost:8090}/.well-known/jwks.json
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=8h